version: '3.8'
services:
  postgres:
    image: postgres:latest
    container_name: postgres-senior
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ${DESAFIO_SENIOR}
      POSTGRES_USER: ${DESAFIO_SENIOR_USER}
      POSTGRES_PASSWORD: ${DESAFIO_SENIOR_PASS}
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:

